### ISSUE TITLE
Edit / Create Page for Surveys

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#1528]
We will implement a edit / create surveys page without attachment.

**Comment by dkatzberg** [comment]
There are some little things to optimize:
- [ ] Unknown I18nString
  - [ ] {{survey-management.error.survey.response-rate.min}}
  - [ ] {{survey-management.error.survey.sample-size.min}}
  - [ ] {{survey-management.error.survey.gross-sample-size.invalid-number}}
  - [ ] {{survey-management.error.survey.gross-sample-size.min}}
- [ ] There is a wrong message on the "language" chooser on the attachment upload I entered a Iso normed String. This error is displayed into the screenshot. This happens on the study and survey page
- [ ] There is a Title () in the Survey Attachment Upload. It looks like a function call.
- [ ] There should be a validator for Responserate (a value over 100% makes no sense!)

**Comment by rreitmann** [comment]
@dkatzberg Fixed please retest...

**Comment by kimsommer** [comment]
**survey page**
-  hyphenation doesn't work when language of attachment is not german or englisch
![unbenannt](https://user-images.githubusercontent.com/19772575/35975719-fbc127d8-0cdd-11e8-8972-594319225e64.png)

**edit survey page**
- it would be cool if response rate was calculated automatically when gross sample size and net sample size are given [#1544](https://github.com/dzhw/metadatamanagement/issues/1544)
- is it necesarry to have a validator to ensure that gross sample size > net sample size ?

**images**
- "Laden Sie eine grafische Darstellung (SVG) des Verlaufs des Rücklaufs (auf Deutsch) hoch.":  maybe rather without "des Verlaufs" because it is a bit long and the englisch text is also without "Verlauf"

**attachments**
- title is missing the mandatory -*

**Firefox**
- responserate diagram cards are somehow small
![unbenannt](https://user-images.githubusercontent.com/19772575/35977365-3d9f303c-0ce3-11e8-8f99-0c762b7ee811.png)
- Gross Sample Size, Net Sample Size and Response Rate: arrows to choose numbers are permanently visible

**Edge**
- small responserate digram cards - same as in Firebox
- Gross Sample Size, Net Sample Size and Response Rate don't have those arrows to choose numbers

**io-wiki**
- title must be mandatory
- sample size must be changed to gross sample size (not mandatory) and net sample size (mandatory)
- field population doesn't exist, only population.title and .description
- I cannot find anything about images

**Comment by rreitmann** [comment]
We need to remove the svg extension from all responserate image in the db since we will allow all kinds of images:
```javascript
db.fs.files.find({"filename": { $regex: /^\/surveys\/.*_responserate_/ }}).forEach(function(file) {
    print("Found file" + file.filename);
    var oldFilename = file.filename;
    var newFilename = file.filename.replace(".svg","");
    print("New filename" + newFilename);
    db.fs.files.update({"filename": oldFilename},{$set: {"filename": newFilename}});
})
```

**Comment by kimsommer** [comment]
- [ ] now I get an error 500 when I modify the attachments and want to save them (and changes aren't saved or sometimes after deleting an attachment the save button doesn't even get active)

**Comment by rreitmann** [comment]
@kimsommer I cannot reproduce what you describe. See here: https://metadatamanagement-test.cfapps.io/#!/de/surveys/sur-gra2005-sy1$/edit

**Comment by rreitmann** [comment]
@kimsommer Here are my first review remarks:
- we need to figure out how we do dependency management cause I had to manually install every r package we need (have a look on packrat)
- please make all attributes in the classes private like you did for variable (same with I18nString,...)
- split utils in at least stata_utils, excel_utils and calculate*
- print error messages when no excel file could be found and no stata file could be found in the given directory
- when sourcing external scripts we need to get the current scripts directory (see https://stackoverflow.com/questions/1815606/rscript-determine-path-of-the-executing-script)
- every script needs to include its dependencies so that it passes linting and can be sourced in R studio without sourcing anything else, I have already reworked this file:
https://github.com/dzhw/variable-generation/blob/master/R/classes/Distribution.R
Please do the same for the other ones...

**Comment by kimsommer** [comment]
It happened with this study:
https://metadatamanagement-test.cfapps.io/#!/de/surveys/sur-test2-sy1$/edit
Error message:
`{"timestamp":"2018-02-14T08:11:52.187+0000","status":500,"error":"Internal Server Error","exception":"java.lang.NullPointerException","message":"No message available","path":"/api/surveys/sur-test2-sy1$/attachments/2_responserate_de.svg"}`

**Comment by dkatzberg** [comment]
Here is the depending error message from the pivotal log:
`2018-02-14T09:04:47.062+01:00 [RTR/10] [OUT] metadatamanagement-test.cfapps.io - [2018-02-14T08:04:47.041+0000] "PUT /api/surveys/sur-test2-sy1$/attachments/4_responserate_en.svg HTTP/1.1" 500 422 208 "https://metadatamanagement-test.cfapps.io/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" "[Removed]" x_forwarded_for:"[Removed]" x_forwarded_proto:"https" vcap_request_id:"[Removed]" response_time:0.020616394 app_id:"[Removed]" app_index:"1" x_b3_traceid:"[Removed]" x_b3_spanid:"[Removed]" x_b3_parentspanid:"-"
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.cloudfoundry.router.ClientCertificateMapper.doFilter(ClientCertificateMapper.java:77)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at java.lang.Thread.run(Thread.java:748)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] ERROR 19 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] java.lang.NullPointerException: null
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at eu.dzhw.fdz.metadatamanagement.surveymanagement.service.SurveyAttachmentService.updateAttachmentMetadata(SurveyAttachmentService.java:138)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at eu.dzhw.fdz.metadatamanagement.surveymanagement.rest.SurveyAttachmentResource.update(SurveyAttachmentResource.java:132)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at eu.dzhw.fdz.metadatamanagement.surveymanagement.rest.SurveyAttachmentResource$$FastClassBySpringCGLIB$$d88a00f3.invoke(<generated>)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
2018-02-14T09:04:47.064+01:00 [APP/PROC/WEB/1] [OUT] at com.ryantenney.metrics.spring.TimedMethodInterceptor.invoke(TimedMethodInterceptor.java:48)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at com.ryantenney.metrics.spring.TimedMethodInterceptor.invoke(TimedMethodInterceptor.java:34)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at com.ryantenney.metrics.spring.AbstractMetricMethodInterceptor.invoke(AbstractMetricMethodInterceptor.java:59)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at eu.dzhw.fdz.metadatamanagement.surveymanagement.rest.SurveyAttachmentResource$$EnhancerBySpringCGLIB$$32f5392c.update(<generated>)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at java.lang.reflect.Method.invoke(Method.java:498)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:883)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at javax.servlet.http.HttpServlet.service(HttpServlet.java:664)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:111)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:176)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
2018-02-14T09:04:47.065+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.web.access.channel.ChannelProcessingFilter.doFilter(ChannelProcessingFilter.java:157)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.cloudfoundry.router.ClientCertificateMapper.doFilter(ClientCertificateMapper.java:77)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2018-02-14T09:04:47.066+01:00 [APP/PROC/WEB/1] [OUT] at java.lang.Thread.run(Thread.java:748)`
